# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Debug'
  NAMECHEAPDOTNET_apiUser: $(namecheap.apiuser)
  NAMECHEAPDOTNET_apiKey: $(namecheap.apikey)
  NAMECHEAPDOTNET_clientIp: $(namecheap.clientip)

steps:
- script: echo "clientip - $(namecheap.clientip) $NAMECHEAPDOTNET_clientIp"
  displayName: 'show vars'
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
#- script: dotnet test
#  displayName: 'dotnet tests'
